Transform: AWS::Serverless-2016-10-31

Description:
  Retornar informações de cursos
Resources:
  AmazonLexBobFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: amazon-lex-bob # nome da função
      Description: Integração Amazon Lex
      CodeUri: ./app # localização local do código da função
      Handler: lambda_function.lambda_handler # nome do arquivo e nome da função que será executada
      Runtime: python3.7 # runtime de execução
      Timeout: 30
      Role: !Sub arn:aws:iam::${AWS::AccountId}:role/LabRole # Papel de execução - permissão para acessar serviços da AWS
      FunctionUrlConfig: # url da funcao
        AuthType: NONE
        Cors:
          AllowMethods:
            - "GET"
            - "POST"
          AllowOrigins:
            - "*"
      Layers:
        - arn:aws:lambda:us-east-1:242841987931:layer:crawler-lib:1
      
Outputs:
  NomeFuncao:
    Description: Nome da função criada
    Value: !Ref AmazonLexBobFunction
  FunctionUrlEndpoint:
      Description: URL do endpoint da Funcao
      Value:
        Fn::GetAtt: AmazonLexBobFunctionUrl.FunctionUrl


